version: '3'

services:
  app:
    build:
      context: ./
    container_name: tenderhack_backend
    ports:
      - "8000:80"
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: always
    networks:
      default:

  llm:
    build:
      context: ./llm
    container_name: tenderhack_llm
    depends_on:
      - rabbitmq
    env_file:
      - .env
    restart: always
    networks:
      default:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBIT_MQ_ERLANG_COOKIE='secret cookie here'
    networks:
      default:
